---
- name: Include fact-global
  ansible.builtin.import_tasks: fact-global.yml

- name: Include distro tasks
  ansible.builtin.include_tasks: setup-{{ _global_distribution }}.yml

- name: Ensure k9s directories are created
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ k9s_cache_path }}"
    - "{{ k9s_installation_path }}"

- name: Ensure k9s is installed
  ansible.builtin.get_url:
    url: "{{ _source_url }}/{{ _github_namespace }}/releases/download/{{ k9s_version }}/{{ _asset_name }}"
    dest: "{{ k9s_cache_path }}"
    checksum: "{{ k9s_checksum }}"
    mode: "0755"

- name: Unarchive k9s archive into k9s_installation_path
  ansible.builtin.unarchive:
    src: "{{ k9s_cache_path }}/{{ _asset_name }}"
    dest: "{{ k9s_installation_path }}"
    remote_src: true
    mode: "0755"

- name: Ensure k9s link is created
  ansible.builtin.file:
    src: "{{ k9s_installation_path }}/{{ _binary_name }}"
    dest: "/usr/local/bin/{{ _binary_name }}"
    state: link
