---
- name: Verify
  hosts: all
  gather_facts: true
  tasks:
    - name: Run kubectl as a privileged user
      become: true
      become_user: root
      block:
        - name: Am I privileged ? # noqa: no-changed-when
          ansible.builtin.command:
            cmd: whoami
          register: whoami_result_priv
          ignore_errors: true
        - name: Run kubectl (privileged user) # noqa: no-changed-when
          ansible.builtin.command:
            cmd: kubectl version --short=true --client=true
          register: kubectl_result_priv
          ignore_errors: true
        - name: Ensure kubectl is installed and running (privileged user)
          ansible.builtin.assert:
            that:
              - kubectl_result_priv.rc == 0
            fail_msg: "kubectl does not seem to be available for the user {{ whoami_result_priv.stdout }}"
            success_msg: "kubectl is available for the user {{ whoami_result_priv.stdout }} : {{ kubectl_result_priv.stdout }}"
    - name: Run kubectl as a non-privileged user
      become: true
      become_user: pandemonium
      block:
        - name: Am I without privilege ? # noqa: no-changed-when
          ansible.builtin.command:
            cmd: whoami
          register: whoami_result_nopriv
          ignore_errors: true
        - name: Run kubectl (non-privileged user) # noqa: no-changed-when
          ansible.builtin.command:
            cmd: kubectl version --short=true --client=true
          register: kubectl_result_nopriv
          ignore_errors: true
        - name: Ensure kubectl is installed and running (non-privileged user)
          ansible.builtin.assert:
            that:
              - kubectl_result_nopriv.rc == 0
            fail_msg: "kubectl does not seem to be available for the user {{ whoami_result_nopriv.stdout }}"
            success_msg: "kubectl is available for the user {{ whoami_result_nopriv.stdout }} : {{ kubectl_result_nopriv.stdout }}"
