---
- name: Verify
  hosts: all
  gather_facts: true
  tasks:
    - name: Run k9s as a privileged user
      become: true
      become_user: root
      block:
        - name: Am I privileged ? # noqa: no-changed-when
          ansible.builtin.command:
            cmd: whoami
          register: whoami_result_priv
          ignore_errors: true
        - name: Run k9s (privileged user) # noqa: no-changed-when
          ansible.builtin.command:
            cmd: /usr/local/bin/k9s version -s
          register: k9s_result_priv
          ignore_errors: true
        - name: Ensure k9s is installed and running (privileged user)
          ansible.builtin.assert:
            that:
              - k9s_result_priv.rc == 0
            fail_msg: "k9s does not seem to be available for the user {{ whoami_result_priv.stdout }}"
            success_msg: "k9s is available for the user {{ whoami_result_priv.stdout }} : {{ k9s_result_priv.stdout }}"
    - name: Run k9s as a non-privileged user
      become: true
      become_user: pandemonium
      block:
        - name: Am I without privilege ? # noqa: no-changed-when
          ansible.builtin.command:
            cmd: whoami
          register: whoami_result_nopriv
          ignore_errors: true
        - name: Run k9s (non-privileged user) # noqa: no-changed-when
          ansible.builtin.command:
            cmd: /usr/local/bin/k9s version -s
          register: k9s_result_nopriv
          ignore_errors: true
        - name: Ensure k9s is installed and running (non-privileged user)
          ansible.builtin.assert:
            that:
              - k9s_result_nopriv.rc == 0
            fail_msg: "k9s does not seem to be available for the user {{ whoami_result_nopriv.stdout }}"
            success_msg: "k9s is available for the user {{ whoami_result_nopriv.stdout }} : {{ k9s_result_nopriv.stdout }}"
