---
- name: Verify
  hosts: all
  gather_facts: true
  tasks:
    - name: Run kubectx as a privileged user
      become: true
      become_user: root
      block:
        - name: Am I privileged ? # noqa: no-changed-when
          ansible.builtin.command:
            cmd: whoami
          register: whoami_result_priv
          ignore_errors: true
        - name: Run kubectx (privileged user) # noqa: no-changed-when
          ansible.builtin.command:
            cmd: /usr/local/bin/kubectx
          no_log: true
          register: kubectx_result_priv
          ignore_errors: true
        - name: Ensure kubectx is installed and running (privileged user)
          ansible.builtin.assert:
            that:
              - kubectx_result_priv.stderr == "kubectl is not installed"
            fail_msg: "kubectx does not seem to be available for the user {{ whoami_result_priv.stdout }}"
            success_msg: "kubectx is available for the user {{ whoami_result_priv.stdout }}"
    - name: Run kubectx as a non-privileged user
      become: true
      become_user: pandemonium
      block:
        - name: Am I without privilege ? # noqa: no-changed-when
          ansible.builtin.command:
            cmd: whoami
          register: whoami_result_nopriv
          ignore_errors: true
        - name: Run kubectx (non-privileged user) # noqa: no-changed-when
          ansible.builtin.command:
            cmd: /usr/local/bin/kubectx
          no_log: true
          register: kubectx_result_nopriv
          ignore_errors: true
        - name: Ensure kubectx is installed and running (non-privileged user)
          ansible.builtin.assert:
            that:
              - kubectx_result_priv.stderr == "kubectl is not installed"
            fail_msg: "kubectx does not seem to be available for the user {{ whoami_result_nopriv.stdout }}"
            success_msg: "kubectx is available for the user {{ whoami_result_nopriv.stdout }}"
