---
# https://github.com/stern/stern
stern_cache_path: "/var/cache/github"
stern_installation_path: "/opt/github/stern"
stern_checksum: "sha256:1501989591f7cf9b946ff38c24453cda0c672932acf2271ef6e894f5cfb384ed"
stern_version: "1.28.0"
