---
- name:              Verify
  hosts:             all
  gather_facts:      true
  tasks:
  - name:            Run kubectx as a privileged user
    block:
    - name:          Am I privileged ?
      command:
        cmd:         whoami
      register:      whoami_result_priv
      ignore_errors: true
    - name:          Run kubectx (privileged user)
      command:
        cmd:         /usr/local/bin/kubectx
      register:      kubectx_result_priv
      ignore_errors: true
    - name:          Ensure kubectx is installed and running (privileged user)
      assert:
        that:
        - kubectx_result_priv.rc == 0
        fail_msg:    "kubectx does not seem to be available for the user {{ whoami_result_priv.stdout }}"
        success_msg:  "kubectx is available for the user {{ whoami_result_priv.stdout }}"
    become:          true
    become_user:     root
  - name:            Run kubectx as a non-privileged user
    block:
    - name:          Am I without privilege ?
      command:
        cmd:         whoami
      register:      whoami_result_nopriv
      ignore_errors: true
    - name:          Run kubectx (non-privileged user)
      command:
        cmd:         /usr/local/bin/kubectx
      register:      kubectx_result_nopriv
      ignore_errors: true
    - name:          Ensure kubectx is installed and running (non-privileged user)
      assert:
        that:
        - kubectx_result_nopriv.rc == 0
        fail_msg:    "kubectx does not seem to be available for the user {{ whoami_result_nopriv.stdout }}"
        success_msg:  "kubectx is available for the user {{ whoami_result_nopriv.stdout }}"
    become:          true
    become_user:     pandemonium
