---
- name: Ensure apt-transport-https is installed
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gpg
    update_cache: true
    state: present

- name: Add Kubernetes apt repository key.
  ansible.builtin.get_url:
    url: "{{ _apt_key_url }}"
    dest: /etc/apt/trusted.gpg.d/kubernetes-apt-keyring.asc
    mode: '0644'
    force: true

- name: Ensure kubernetes dists are enabled
  ansible.builtin.apt_repository:
    repo: "deb https://pkgs.k8s.io/core:/stable:/v{{ _kubectl_major_version }}/deb/ /"
    state: present
    filename: kubernetes

- name: Ensure kubectl is installed
  ansible.builtin.apt:
    name: "kubectl={{ kubectl_version }}-1.1"
    update_cache: true
    state: present
