---
- name: Ensure apt-transport-https is installed
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - gpg
    update_cache: true
    state: present

- name: Ensure packages.cloud.google.com key is added
  ansible.builtin.apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Ensure kubernetes dists are enabled
  ansible.builtin.apt_repository:
    repo: "deb https://apt.kubernetes.io/ kubernetes-{{ apt_dists }} main"
    state: present
    filename: kubernetes

- name: Ensure kubectl is installed
  ansible.builtin.apt:
    name: "kubectl={{ kubectl_version }}-00"
    update_cache: true
    state: present
