---
- name: Ensure kubernetes repo are enabled
  ansible.builtin.yum_repository:
    name: Kubernetes
    description: Google Kubernetes repo
    baseurl: "https://pkgs.k8s.io/core:/stable:/v{{ _kubectl_major_version }}/rpm/"
    enabled: true
    gpgcheck: true
    gpgkey: "{{ _yum_key_url }}"

- name: Ensure kubectl is installed
  ansible.builtin.yum:
    name: "kubectl-{{ kubectl_version }}"
    update_cache: true
    state: present
