---
- name: Ensure kubernetes repo are enabled
  community.general.zypper_repository:
    name: Kubernetes
    description: Google Kubernetes repo
    repo: "https://pkgs.k8s.io/core:/stable:/v{{ _kubectl_major_version }}/rpm/"
    enabled: true
    auto_import_keys: true

- name: Ensure kubectl is installed
  community.general.zypper:
    name: "kubectl-{{ kubectl_version }}"
    update_cache: true
    state: present
