---
dependency:
  name: galaxy
  enabled: false
driver:
  name: docker
platforms:
  - name: molecule-${DKR_IMAGE:-debian12}
    hostname: ${DKR_IMAGE:-debian12}
    image: ${DKR_REGISTRY:-ghcr.io/pandemonium1986}/${DKR_IMAGE:-debian12}:${DKR_TAG:-nightly}
    pull: ${DKR_PULL_IMAGE:-true}
    pre_build_image: true
    tty: true
    override_command: false
    tmpfs:
      - /run
      - /tmp
    privileged: true
provisioner:
  name: ansible
  config_options:
    defaults:
      stdout_callback: yaml
      bin_ansible_callbacks: true
scenario:
  name: default
verifier:
  name: ansible
  enabled: true
