---
- name: Configure facts for any distribution
  ansible.builtin.set_fact:
    _global_distribution: "{{ ansible_distribution | lower }}"
    _global_os_family: "{{ ansible_os_family | lower }}"
    _global_distribution_version: "{{ ansible_distribution_version.split('.')[0] | lower }}"

- name: Configure special facts for openSUSE/SLES distributions
  ansible.builtin.set_fact:
    _global_distribution: "suse"
    _global_os_family: "suse"
  when: ansible_distribution_file_variety == 'SUSE'

- name: Configure special facts for tumbleweed distribution
  ansible.builtin.set_fact:
    _global_distribution_version: "tumbleweed"
  when: ansible_distribution == 'openSUSE Tumbleweed'
