---
- name:              Verify
  hosts:             all
  gather_facts:      true
  tasks:
  - name:            Run kubectl as a privileged user
    block:
    - name:          Am I privileged ?
      command:
        cmd:         whoami
      register:      whoami_result_priv
      ignore_errors: true
    - name:          Run kubectl (privileged user)
      command:
        cmd:         kubectl version --short=true --client=true
      register:      kubectl_result_priv
      ignore_errors: true
    - name:          Ensure kubectl is installed and running (privileged user)
      assert:
        that:
        - kubectl_result_priv.rc == 0
        fail_msg:    "kubectl does not seem to be available for the user {{ whoami_result_priv.stdout }}"
        success_msg:  "kubectl is available for the user {{ whoami_result_priv.stdout }} : {{ kubectl_result_priv.stdout }}"
    become:          true
    become_user:     root
  - name:            Run kubectl as a non-privileged user
    block:
    - name:          Am I without privilege ?
      command:
        cmd:         whoami
      register:      whoami_result_nopriv
      ignore_errors: true
    - name:          Run kubectl (non-privileged user)
      command:
        cmd:         kubectl version --short=true --client=true
      register:      kubectl_result_nopriv
      ignore_errors: true
    - name:          Ensure kubectl is installed and running (non-privileged user)
      assert:
        that:
        - kubectl_result_nopriv.rc == 0
        fail_msg:    "kubectl does not seem to be available for the user {{ whoami_result_nopriv.stdout }}"
        success_msg:  "kubectl is available for the user {{ whoami_result_nopriv.stdout }} : {{ kubectl_result_nopriv.stdout }}"
    become:          true
    become_user:     pandemonium
