---
# https://github.com/helm/helm
helm_cache_path: "/var/cache/github"
helm_installation_path: "/opt/github/helm"
helm_checksum: "sha256:98c363564d00afd0cc3088e8f830f2a0eeb5f28755b3d8c48df89866374a1ed0"
helm_version: "v3.13.1"
