---
name: "Molecule Workflow"
on:
  schedule:
    - cron: "0 21 * * *"
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  called-linter:
    permissions:
      contents: read
      packages: read
      statuses: write
    name: "Called: GitHub Super Linter Workflow"
    uses: pandemonium1986/.github/.github/workflows/called-linter.yml@main
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
  molecule:
    name: "Molecule: Test"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        images:
          - "centos7"
          - "debian12"
          - "ubuntu2204"
          - "sles15sp3"
          - "sles15sp5"
          - "tumbleweed"
    container:
      image: ghcr.io/pandemonium1986/alpine318:2.0.0
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ${{ github.workspace }}:/opt/workspace/${{ github.repository }}
      env:
        ANSIBLE_FORCE_COLOR: "1"
        PY_COLORS: "1"
        DKR_IMAGE: ${{ matrix.images }}
        DKR_TAG: "nightly"
      options: >-
        --workdir /opt/workspace/${{ github.repository }}
    needs:
      - called-linter
    steps:
      - name: "Init: Run checkout"
        uses: actions/checkout@v4
      - name: "Molecule: Create"
        run: molecule create
      - name: "Molecule: Converge"
        run: molecule converge
      - name: "Molecule: Idempotence"
        run: molecule idempotence
      - name: "Molecule: Verify"
        run: molecule verify
      - name: "Molecule: Destroy"
        run: molecule destroy
