---
- name: Include fact-global
  ansible.builtin.import_tasks: fact-global.yml

- name: Ensure minikube is installed according to the variety of the OS
  ansible.builtin.include_tasks: setup-{{ _global_os_family }}.yml
