---
- name: Ensure apt-transport-https is installed
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - gpg
    update_cache: true
    state: present

- name: Ensure minikube is installed
  ansible.builtin.apt:
    deb: "https://storage.googleapis.com/minikube/releases/v{{ minikube_version }}/minikube_{{ minikube_version }}-0_amd64.deb"
    state: present
