---
- name:       Ensure stern directories are created
  file:
    path:     "{{ stern_installation_path }}"
    state:    directory
    mode:     "0755"

- name:       Ensure stern is installed
  get_url:
    url:      "{{ source_url }}/{{ github_namespace }}/releases/download/{{ stern_version }}/{{ asset_name }}"
    dest:     "{{ stern_installation_path }}/{{ asset_name }}"
    checksum: "{{ stern_checksum }}"
    mode:     "0755"

- name:       Ensure stern link is created
  file:
    src:      "{{ stern_installation_path }}/{{ asset_name }}"
    dest:     "/usr/local/bin/{{ binary_name }}"
    state:    link
