---
- name: Verify
  hosts: all
  gather_facts: true
  tasks:
    - name: Run helm as a privileged user
      become: true
      become_user: root
      block:
        - name: Am I privileged ? # noqa: no-changed-when
          ansible.builtin.command:
            cmd: whoami
          register: whoami_result_priv
          ignore_errors: true
        - name: Run helm (privileged user) # noqa: no-changed-when
          ansible.builtin.command:
            cmd: /usr/local/bin/helm version --short
          register: helm_result_priv
          ignore_errors: true
        - name: Ensure helm is installed and running (privileged user)
          ansible.builtin.assert:
            that:
              - helm_result_priv.rc == 0
            fail_msg: "helm does not seem to be available for the user {{ whoami_result_priv.stdout }}"
            success_msg: "helm is available for the user {{ whoami_result_priv.stdout }} : {{ helm_result_priv.stdout }}"
    - name: Run helm as a non-privileged user
      become: true
      become_user: pandemonium
      block:
        - name: Am I without privilege ? # noqa: no-changed-when
          ansible.builtin.command:
            cmd: whoami
          register: whoami_result_nopriv
          ignore_errors: true
        - name: Run helm (non-privileged user) # noqa: no-changed-when
          ansible.builtin.command:
            cmd: /usr/local/bin/helm version --short
          register: helm_result_nopriv
          ignore_errors: true
        - name: Ensure helm is installed and running (non-privileged user)
          ansible.builtin.assert:
            that:
              - helm_result_nopriv.rc == 0
            fail_msg: "helm does not seem to be available for the user {{ whoami_result_nopriv.stdout }}"
            success_msg: "helm is available for the user {{ whoami_result_nopriv.stdout }} : {{ helm_result_nopriv.stdout }}"
