---
name: "Collection deployment"

on:
  release:
    types:
      - published

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Init: Run checkout@v2"
        uses: actions/checkout@v4
      - name: "Init: Get the version from the tag"
        run: echo RELEASE_VERSION=${GITHUB_REF/refs\/tags\//} >> $GITHUB_ENV
      - name: "Ansible: deploy collection in galaxy"
        uses: artis3n/ansible_galaxy_collection@v2
        with:
          api_key: ${{ secrets.GALAXY_API_KEY }}
          galaxy_version: ${{ env.RELEASE_VERSION }}
